"""Train CatBoost prop models with walk-forward CV and optional unified cross-stat model."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, Pool
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score

from feature_schema import (
    CATEGORICAL_FEATURE_COLUMNS,
    DEFAULT_DATASET_PATH,
    DEFAULT_MODEL_DIR,
    FEATURE_GROUPS,
    MODEL_FEATURE_COLUMNS,
    MODEL_TARGET_COLUMN,
)


DEFAULT_TOP_K_VALUES = [5, 10, 25]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train per-stat CatBoost models from the generated prop dataset.",
    )
    parser.add_argument(
        "--dataset-csv",
        default=str(DEFAULT_DATASET_PATH),
        help="Input dataset generated by build_prop_dataset.py.",
    )
    parser.add_argument(
        "--model-dir",
        default=str(DEFAULT_MODEL_DIR),
        help="Output directory for .cbm models and metadata JSON.",
    )
    parser.add_argument(
        "--test-date-count",
        type=int,
        default=2,
        help="Number of most recent slate dates held out for evaluation per stat type.",
    )
    parser.add_argument(
        "--min-train-dates",
        type=int,
        default=2,
        help="Minimum number of training dates required before the holdout window.",
    )
    parser.add_argument(
        "--min-train-rows",
        type=int,
        default=150,
        help="Skip a stat type if its training split is smaller than this row count.",
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=800,
        help="CatBoost boosting iterations.",
    )
    parser.add_argument(
        "--depth",
        type=int,
        default=6,
        help="CatBoost tree depth.",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=0.03,
        help="CatBoost learning rate.",
    )
    parser.add_argument(
        "--l2-leaf-reg",
        type=float,
        default=8.0,
        help="CatBoost L2 regularization.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed.",
    )
    parser.add_argument(
        "--feature-groups",
        nargs="*",
        default=["market", "player_form", "usage", "momentum", "consistency"],
        choices=sorted(FEATURE_GROUPS.keys()),
        help="Feature groups to include in this experiment.",
    )
    parser.add_argument(
        "--top-k",
        nargs="*",
        type=int,
        default=DEFAULT_TOP_K_VALUES,
        help="K values used for holdout top-K hit-rate/ROI summaries.",
    )
    parser.add_argument(
        "--unified",
        action="store_true",
        default=False,
        help="Train a single unified model across all stat types instead of per-stat models.",
    )
    parser.add_argument(
        "--walk-forward",
        action="store_true",
        default=False,
        help="Use walk-forward expanding-window CV instead of fixed holdout.",
    )
    parser.add_argument(
        "--calibrate",
        action="store_true",
        default=False,
        help="Apply isotonic calibration to predicted probabilities.",
    )
    parser.add_argument(
        "--walk-forward-min-train-dates",
        type=int,
        default=3,
        help="Minimum training dates before first walk-forward test fold.",
    )
    return parser.parse_args()


def _stat_model_slug(stat_type: str) -> str:
    return stat_type.lower().replace("+", "_plus_").replace("/", "_")


def _selected_feature_columns(feature_groups: Sequence[str]) -> List[str]:
    selected = list(CATEGORICAL_FEATURE_COLUMNS)
    seen = set(selected)
    for group_name in feature_groups:
        for column_name in FEATURE_GROUPS.get(group_name, []):
            if column_name not in seen:
                selected.append(column_name)
                seen.add(column_name)
    return selected


def _load_dataset(dataset_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(dataset_csv)
    df["game_date"] = pd.to_datetime(df["game_date"], errors="coerce")
    df = df[df["game_date"].notna()].copy()
    df = df[df["result_status"].isin(["hit", "miss"])].copy()
    df[MODEL_TARGET_COLUMN] = pd.to_numeric(df[MODEL_TARGET_COLUMN], errors="coerce")
    df = df[df[MODEL_TARGET_COLUMN].isin([0, 1])].copy()
    return df


def _prepare_feature_frame(df: pd.DataFrame, feature_columns: Sequence[str]) -> pd.DataFrame:
    X = df.loc[:, feature_columns].copy()
    for column_name in feature_columns:
        if column_name in CATEGORICAL_FEATURE_COLUMNS or column_name == "stat_type":
            X[column_name] = X[column_name].fillna("UNKNOWN").astype(str)
        else:
            X[column_name] = pd.to_numeric(X[column_name], errors="coerce")
    return X


def _date_holdout_split(
    df: pd.DataFrame,
    *,
    test_date_count: int,
    min_train_dates: int,
) -> Optional[Tuple[pd.DataFrame, pd.DataFrame, str]]:
    unique_dates = sorted(df["game_date"].dt.date.unique())
    if len(unique_dates) <= min_train_dates:
        return None

    split_index = max(min_train_dates, len(unique_dates) - max(1, test_date_count))
    if split_index >= len(unique_dates):
        return None

    split_date = pd.Timestamp(unique_dates[split_index])
    train_df = df[df["game_date"] < split_date].copy()
    test_df = df[df["game_date"] >= split_date].copy()
    if train_df.empty or test_df.empty:
        return None
    return train_df, test_df, split_date.date().isoformat()


def _walk_forward_splits(
    df: pd.DataFrame,
    *,
    min_train_dates: int,
) -> List[Tuple[pd.DataFrame, pd.DataFrame, str]]:
    """Generate expanding-window walk-forward splits.

    Each fold uses all dates before a test date as training,
    and a single date as the test set.
    """
    unique_dates = sorted(df["game_date"].dt.date.unique())
    splits = []

    for test_idx in range(min_train_dates, len(unique_dates)):
        test_date = unique_dates[test_idx]
        split_date = pd.Timestamp(test_date)
        train_df = df[df["game_date"] < split_date].copy()
        test_df = df[df["game_date"] == split_date].copy()
        if train_df.empty or test_df.empty:
            continue
        splits.append((train_df, test_df, test_date.isoformat()))

    return splits


def _safe_metric(value: Any) -> Optional[float]:
    if value is None:
        return None
    parsed = float(value)
    if math.isnan(parsed) or math.isinf(parsed):
        return None
    return round(parsed, 6)


def _topk_metrics(
    test_df: pd.DataFrame,
    predicted_probabilities: Sequence[float],
    top_k_values: Sequence[int],
) -> Dict[str, Dict[str, Optional[float]]]:
    scored_df = test_df[["game_date", "hit_label", "payout_decimal"]].copy()
    scored_df["predicted_hit_prob"] = list(predicted_probabilities)
    scored_df["payout_decimal"] = pd.to_numeric(scored_df["payout_decimal"], errors="coerce").fillna(1.0)
    scored_df["predicted_ev"] = (
        scored_df["predicted_hit_prob"] * scored_df["payout_decimal"]
    ) - (1.0 - scored_df["predicted_hit_prob"])
    scored_df["realized_profit"] = scored_df.apply(
        lambda row: float(row["payout_decimal"]) if int(row["hit_label"]) == 1 else -1.0,
        axis=1,
    )

    metrics: Dict[str, Dict[str, Optional[float]]] = {}
    for top_k in top_k_values:
        if top_k <= 0:
            continue
        daily_returns = []
        daily_hit_rates = []
        daily_avg_ev = []
        daily_bet_counts = []

        for _, day_df in scored_df.groupby(scored_df["game_date"].dt.date):
            top_df = day_df.sort_values("predicted_ev", ascending=False).head(top_k)
            if top_df.empty:
                continue
            daily_returns.append(float(top_df["realized_profit"].mean()))
            daily_hit_rates.append(float(top_df["hit_label"].mean()))
            daily_avg_ev.append(float(top_df["predicted_ev"].mean()))
            daily_bet_counts.append(int(len(top_df)))

        metric_key = f"top_{top_k}"
        metrics[metric_key] = {
            "avg_daily_hit_rate": _safe_metric(sum(daily_hit_rates) / len(daily_hit_rates)) if daily_hit_rates else None,
            "avg_daily_roi_per_bet": _safe_metric(sum(daily_returns) / len(daily_returns)) if daily_returns else None,
            "avg_daily_predicted_ev": _safe_metric(sum(daily_avg_ev) / len(daily_avg_ev)) if daily_avg_ev else None,
            "avg_daily_bets": _safe_metric(sum(daily_bet_counts) / len(daily_bet_counts)) if daily_bet_counts else None,
            "evaluated_days": len(daily_returns),
        }
    return metrics


def _compute_metrics(
    y_test: np.ndarray,
    test_probs: np.ndarray,
    test_df: pd.DataFrame,
    top_k_values: Sequence[int],
    stat_type: str,
    split_date: str,
    train_rows: int,
    test_rows: int,
    train_dates: int,
    test_dates: int,
    y_train_mean: float,
    best_iteration: int,
) -> Dict[str, Any]:
    label_values = y_test

    auc_value = None
    if len(set(label_values.tolist())) == 2:
        auc_value = roc_auc_score(label_values, test_probs)

    return {
        "stat_type": stat_type,
        "split_date": split_date,
        "train_rows": train_rows,
        "test_rows": test_rows,
        "train_dates": train_dates,
        "test_dates": test_dates,
        "positive_rate_train": _safe_metric(y_train_mean),
        "positive_rate_test": _safe_metric(float(y_test.mean())),
        "auc": _safe_metric(auc_value),
        "brier": _safe_metric(brier_score_loss(label_values, test_probs)),
        "log_loss": _safe_metric(log_loss(label_values, test_probs, labels=[0, 1])),
        "accuracy_at_0_5": _safe_metric(accuracy_score(label_values, test_probs >= 0.5)),
        "topk": _topk_metrics(test_df, test_probs, top_k_values),
        "best_iteration": best_iteration,
    }


def _fit_single_split(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    *,
    feature_columns: Sequence[str],
    cat_feature_indices: Sequence[int],
    args: argparse.Namespace,
) -> Tuple[CatBoostClassifier, np.ndarray, np.ndarray]:
    """Train a CatBoost model on one train/test split and return model + predictions."""
    X_train = _prepare_feature_frame(train_df, feature_columns)
    X_test = _prepare_feature_frame(test_df, feature_columns)
    y_train = train_df[MODEL_TARGET_COLUMN].astype(int)
    y_test = test_df[MODEL_TARGET_COLUMN].astype(int)

    train_pool = Pool(X_train, label=y_train, cat_features=list(cat_feature_indices))
    test_pool = Pool(X_test, label=y_test, cat_features=list(cat_feature_indices))

    model = CatBoostClassifier(
        iterations=args.iterations,
        depth=args.depth,
        learning_rate=args.learning_rate,
        l2_leaf_reg=args.l2_leaf_reg,
        loss_function="Logloss",
        eval_metric="Logloss",
        random_seed=args.seed,
        verbose=False,
        allow_writing_files=False,
    )
    model.fit(
        train_pool,
        eval_set=test_pool,
        use_best_model=True,
        early_stopping_rounds=50,
    )

    test_probs = model.predict_proba(test_pool)[:, 1]

    if args.calibrate and len(y_test) > 10:
        try:
            calibrated = CalibratedClassifierCV(model, method="isotonic", cv="prefit")
            calibrated.fit(X_test, y_test)
            test_probs = calibrated.predict_proba(X_test)[:, 1]
        except Exception:
            pass

    return model, test_probs, y_test.to_numpy()


def _fit_stat_model(
    stat_df: pd.DataFrame,
    *,
    stat_type: str,
    feature_columns: Sequence[str],
    cat_feature_indices: Sequence[int],
    args: argparse.Namespace,
) -> Optional[Dict[str, Any]]:
    split = _date_holdout_split(
        stat_df,
        test_date_count=args.test_date_count,
        min_train_dates=args.min_train_dates,
    )
    if split is None:
        return None

    train_df, test_df, split_date = split
    if len(train_df) < args.min_train_rows:
        return None

    model, test_probs, label_values = _fit_single_split(
        train_df, test_df,
        feature_columns=feature_columns,
        cat_feature_indices=cat_feature_indices,
        args=args,
    )

    y_train = train_df[MODEL_TARGET_COLUMN].astype(int)
    metrics = _compute_metrics(
        label_values, test_probs, test_df, args.top_k,
        stat_type=stat_type,
        split_date=split_date,
        train_rows=int(len(train_df)),
        test_rows=int(len(test_df)),
        train_dates=int(train_df["game_date"].dt.date.nunique()),
        test_dates=int(test_df["game_date"].dt.date.nunique()),
        y_train_mean=float(y_train.mean()),
        best_iteration=int(model.get_best_iteration() or args.iterations),
    )

    return {
        "model": model,
        "metrics": metrics,
        "feature_columns": list(feature_columns),
        "cat_feature_columns": [
            feature_columns[index]
            for index in cat_feature_indices
        ],
    }


def _walk_forward_eval(
    df: pd.DataFrame,
    *,
    stat_type: str,
    feature_columns: Sequence[str],
    cat_feature_indices: Sequence[int],
    args: argparse.Namespace,
) -> Optional[Dict[str, Any]]:
    """Run walk-forward expanding-window cross-validation."""
    splits = _walk_forward_splits(
        df,
        min_train_dates=args.walk_forward_min_train_dates,
    )
    if not splits:
        return None

    all_test_probs = []
    all_labels = []
    all_test_dfs = []
    fold_metrics = []
    final_model = None

    for train_df, test_df, split_date in splits:
        if len(train_df) < args.min_train_rows:
            continue

        model, test_probs, labels = _fit_single_split(
            train_df, test_df,
            feature_columns=feature_columns,
            cat_feature_indices=cat_feature_indices,
            args=args,
        )
        final_model = model
        all_test_probs.extend(test_probs.tolist())
        all_labels.extend(labels.tolist())
        all_test_dfs.append(test_df)

        y_train = train_df[MODEL_TARGET_COLUMN].astype(int)
        fold_metric = _compute_metrics(
            labels, test_probs, test_df, args.top_k,
            stat_type=stat_type,
            split_date=split_date,
            train_rows=int(len(train_df)),
            test_rows=int(len(test_df)),
            train_dates=int(train_df["game_date"].dt.date.nunique()),
            test_dates=1,
            y_train_mean=float(y_train.mean()),
            best_iteration=int(model.get_best_iteration() or args.iterations),
        )
        fold_metrics.append(fold_metric)

    if not all_labels or final_model is None:
        return None

    all_test_probs_arr = np.array(all_test_probs)
    all_labels_arr = np.array(all_labels)
    combined_test_df = pd.concat(all_test_dfs, ignore_index=True)

    auc_value = None
    if len(set(all_labels)) == 2:
        auc_value = roc_auc_score(all_labels_arr, all_test_probs_arr)

    aggregate_metrics = {
        "stat_type": stat_type,
        "method": "walk_forward",
        "num_folds": len(fold_metrics),
        "total_test_rows": len(all_labels),
        "auc": _safe_metric(auc_value),
        "brier": _safe_metric(brier_score_loss(all_labels_arr, all_test_probs_arr)),
        "log_loss": _safe_metric(log_loss(all_labels_arr, all_test_probs_arr, labels=[0, 1])),
        "accuracy_at_0_5": _safe_metric(accuracy_score(all_labels_arr, all_test_probs_arr >= 0.5)),
        "topk": _topk_metrics(combined_test_df, all_test_probs_arr, args.top_k),
        "per_fold_auc": [f.get("auc") for f in fold_metrics],
    }

    return {
        "model": final_model,
        "metrics": aggregate_metrics,
        "feature_columns": list(feature_columns),
        "cat_feature_columns": [
            feature_columns[index]
            for index in cat_feature_indices
        ],
        "fold_metrics": fold_metrics,
    }


def _train_all_stats(df: pd.DataFrame, args: argparse.Namespace) -> Dict[str, Any]:
    feature_columns = [
        column_name
        for column_name in _selected_feature_columns(args.feature_groups)
        if column_name in df.columns
    ]

    # For unified model, add stat_type as a categorical feature
    if args.unified and "stat_type" not in feature_columns:
        feature_columns = ["stat_type"] + feature_columns

    cat_feature_indices = [
        index
        for index, column_name in enumerate(feature_columns)
        if column_name in CATEGORICAL_FEATURE_COLUMNS or column_name == "stat_type"
    ]

    model_dir = Path(args.model_dir)
    model_dir.mkdir(parents=True, exist_ok=True)

    manifest: Dict[str, Any] = {
        "dataset_csv": str(Path(args.dataset_csv).resolve()),
        "model_dir": str(model_dir.resolve()),
        "feature_groups": list(args.feature_groups),
        "feature_columns": feature_columns,
        "cat_feature_columns": [
            feature_columns[index]
            for index in cat_feature_indices
        ],
        "params": {
            "iterations": args.iterations,
            "depth": args.depth,
            "learning_rate": args.learning_rate,
            "l2_leaf_reg": args.l2_leaf_reg,
            "seed": args.seed,
            "test_date_count": args.test_date_count,
            "min_train_dates": args.min_train_dates,
            "min_train_rows": args.min_train_rows,
            "top_k": args.top_k,
            "unified": args.unified,
            "walk_forward": args.walk_forward,
            "calibrate": args.calibrate,
        },
        "stat_models": {},
    }

    if args.unified:
        # Train one model across all stat types
        print(f"UNIFIED MODEL: {len(df)} rows, {df['stat_type'].nunique()} stat types")

        if args.walk_forward:
            fit_result = _walk_forward_eval(
                df,
                stat_type="unified",
                feature_columns=feature_columns,
                cat_feature_indices=cat_feature_indices,
                args=args,
            )
        else:
            fit_result = _fit_stat_model(
                df,
                stat_type="unified",
                feature_columns=feature_columns,
                cat_feature_indices=cat_feature_indices,
                args=args,
            )

        if fit_result is None:
            print("SKIP unified: not enough data")
        else:
            model_path = model_dir / "unified.cbm"
            metadata_path = model_dir / "unified.metadata.json"
            fit_result["model"].save_model(str(model_path))

            metadata = {
                "stat_type": "unified",
                "model_path": str(model_path.resolve()),
                "feature_columns": fit_result["feature_columns"],
                "cat_feature_columns": fit_result["cat_feature_columns"],
                "metrics": fit_result["metrics"],
            }
            metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True))

            manifest["stat_models"]["unified"] = {
                "model_path": str(model_path.resolve()),
                "metadata_path": str(metadata_path.resolve()),
                "metrics": fit_result["metrics"],
            }

            metrics = fit_result["metrics"]
            print(
                f"unified: "
                f"auc={metrics.get('auc')} "
                f"brier={metrics.get('brier')} "
                f"logloss={metrics.get('log_loss')} "
                f"acc={metrics.get('accuracy_at_0_5')} "
                f"top5_roi={metrics.get('topk', {}).get('top_5', {}).get('avg_daily_roi_per_bet')}"
            )

            # Export feature importances
            try:
                importances = fit_result["model"].get_feature_importance()
                importance_pairs = sorted(
                    zip(feature_columns, importances),
                    key=lambda x: x[1],
                    reverse=True,
                )
                importance_path = model_dir / "unified.feature_importance.json"
                importance_path.write_text(json.dumps(
                    [{"feature": name, "importance": round(float(imp), 4)} for name, imp in importance_pairs],
                    indent=2,
                ))
                print(f"  top features: {[f'{n}={round(i, 2)}' for n, i in importance_pairs[:10]]}")
            except Exception as exc:
                print(f"  feature importance export failed: {exc}")
    else:
        # Train per-stat models (original behavior)
        for stat_type in sorted(df["stat_type"].dropna().unique()):
            stat_df = df[df["stat_type"] == stat_type].copy()

            if args.walk_forward:
                fit_result = _walk_forward_eval(
                    stat_df,
                    stat_type=stat_type,
                    feature_columns=feature_columns,
                    cat_feature_indices=cat_feature_indices,
                    args=args,
                )
            else:
                fit_result = _fit_stat_model(
                    stat_df,
                    stat_type=stat_type,
                    feature_columns=feature_columns,
                    cat_feature_indices=cat_feature_indices,
                    args=args,
                )

            if fit_result is None:
                print(f"SKIP {stat_type}: not enough date/row history")
                continue

            stat_slug = _stat_model_slug(stat_type)
            model_path = model_dir / f"{stat_slug}.cbm"
            metadata_path = model_dir / f"{stat_slug}.metadata.json"

            fit_result["model"].save_model(str(model_path))
            metadata = {
                "stat_type": stat_type,
                "model_path": str(model_path.resolve()),
                "feature_columns": fit_result["feature_columns"],
                "cat_feature_columns": fit_result["cat_feature_columns"],
                "metrics": fit_result["metrics"],
            }
            metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True))

            manifest["stat_models"][stat_type] = {
                "model_path": str(model_path.resolve()),
                "metadata_path": str(metadata_path.resolve()),
                "metrics": fit_result["metrics"],
            }

            metrics = fit_result["metrics"]
            print(
                f"{stat_type}: "
                f"auc={metrics.get('auc')} "
                f"brier={metrics.get('brier')} "
                f"logloss={metrics.get('log_loss')} "
                f"acc={metrics.get('accuracy_at_0_5')} "
                f"top5_roi={metrics.get('topk', {}).get('top_5', {}).get('avg_daily_roi_per_bet')}"
            )

    manifest_path = model_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True))
    manifest["manifest_path"] = str(manifest_path.resolve())
    return manifest


def main() -> int:
    args = _parse_args()
    dataset_csv = Path(args.dataset_csv)
    if not dataset_csv.exists():
        raise FileNotFoundError(
            f"Dataset not found: {dataset_csv}. Run build_prop_dataset.py first."
        )

    df = _load_dataset(dataset_csv)
    manifest = _train_all_stats(df, args)
    print(f"manifest={manifest['manifest_path']}")
    print(f"trained_stat_models={len(manifest['stat_models'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
